-- TOPdesk core DAX starter measures
Incident Count = COUNTROWS ( FactIncident )

Open Incident Count =
CALCULATE (
    [Incident Count],
    KEEPFILTERS ( FactIncident[IsOpen] = TRUE () )
)

Closed Incident Count =
CALCULATE (
    [Incident Count],
    KEEPFILTERS ( FactIncident[IsClosed] = TRUE () )
)

SLA Breach Count =
CALCULATE (
    [Incident Count],
    KEEPFILTERS ( FactIncident[IsSlaBreached] = TRUE () )
)

SLA Compliance % =
DIVIDE ( [Closed Incident Count] - [SLA Breach Count], [Closed Incident Count] )

Average Resolution Hours =
AVERAGEX (
    FILTER ( FactIncident, NOT ISBLANK ( FactIncident[ResolutionHours] ) ),
    FactIncident[ResolutionHours]
)

AI Suggestion Acceptance % =
DIVIDE ( [Accepted AI Suggestions], [AI Suggestions] )

