AI Suggestions = COUNTROWS(FactAISuggestion)
AI Prompt Runs = COUNTROWS(FactAIPromptRun)
AI Accepted = CALCULATE([AI Suggestions], FactAISuggestion[feedback_status] = "accepted")
AI Acceptance Rate = DIVIDE([AI Accepted], [AI Suggestions])
AI Eval Cases = COUNTROWS(FactAIEvaluation)
AI Eval Pass Rate = DIVIDE(CALCULATE([AI Eval Cases], FactAIEvaluation[passed] = TRUE()), [AI Eval Cases])
AI Cost = SUM(FactAIPromptRun[cost_amount])
AI Tokens = SUM(FactAIPromptRun[token_count])
AI PII Findings = CALCULATE(COUNTROWS(FactAIRiskFinding), FactAIRiskFinding[finding_type] = "pii")

